// <auto-generated />
using System;
using HostPinger.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostPinger.Core.Migrations
{
    [DbContext(typeof(HostPingerDbContext))]
    [Migration("20260801032327_AddUnansweredPingIndex")]
    partial class AddUnansweredPingIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HostPinger.Core.Data.MonitoredHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("HostPinger.Core.Data.PingAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundtripMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("HostId", "TimestampUtc");

                    b.HasIndex(new[] { "HostId", "TimestampUtc" }, "IX_PingAttempts_Unanswered")
                        .HasFilter("\"RoundtripMs\" IS NULL");

                    b.ToTable("PingAttempts");
                });

            modelBuilder.Entity("HostPinger.Core.Data.PingAttempt", b =>
                {
                    b.HasOne("HostPinger.Core.Data.MonitoredHost", "Host")
                        .WithMany("PingAttempts")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("HostPinger.Core.Data.MonitoredHost", b =>
                {
                    b.Navigation("PingAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
